DROP DATABASE IF EXISTS musics;

CREATE DATABASE musics;
USE musics;

CREATE TABLE score (
  score_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  track_id INT UNSIGNED NOT NULL,
  lyric INT UNSIGNED NOT NULL,
  melody INT UNSIGNED NOT NULL,
  singer INT UNSIGNED NOT NULL,
  mv INT UNSIGNED NOT NULL,
  PRIMARY KEY (score_id)
);

CREATE TABLE review (
  review_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  track_id INT UNSIGNED NOT NULL,
  create_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  content VARCHAR(50000) NOT NULL CHECK (content <> ''),
  PRIMARY KEY (review_id)
);